language: cpp
compiler:
  - gcc
env:
  matrix:
    - CMAKE_ARGS="-DCOVERALLS=ON"
    - CMAKE_ARGS="-DCOVERALLS=OFF"


before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - cd ../bin
  - ./Simple
