language: cpp
compiler:
  - gcc
env:
  matrix:
    - DEBUG="YES"
    - DEBUG="NO"

before_script:
  - mkdir build
  - cd build
  - if [ ${DEBUG} == "YES" ]; then 
    cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug WITH_UNIT_TESTS=ON ..; else
    cmake ..;
    fi


script:
  - make
  - cd ../bin
  - ./Simple
  - if [ ${DEBUG} == "YES" ];
    make coveralls;
    fi
