language: cpp
compiler:
  - gcc
env:
  global:
    - NUM_THREADS=4

    - COVERALLS_SERVICE_NAME=travis-ci
    - COVERALLS_REPO_TOKEN=NXHsGpmqi6PpZHX8iM3OisE48frajQmFl

    - SCRIPTS=${TRAVIS_BUILD_DIR}/travis
    - EXTERNALS_DIR=/home/travis/external

  matrix:
    - VTK_VERSION=6.0 DEBUG="YES"
    - VTK_VERSION=6.3 DEBUG="YES"
    - VTK_VERSION=7.0 DEBUG="YES"
    - VTK_VERSION=6.0 DEBUG="NO"
    - VTK_VERSION=6.3 DEBUG="NO"
    - VTK_VERSION=7.0 DEBUG="NO"

before_install:

  - export VTK_SOURCE_DIR=$EXTERNALS_DIR/vtk-$VTK_VERSION
  - export VTK_DIR=$EXTERNALS_DIR/vtk-$VTK_VERSION-build
  - export TCLLIBPATH=$VTK_DIR/Wrapping/Tcl

install:
  - $SCRIPTS/travis_build_vtk.sh
  - $SCRIPTS/travis_before_script_cleanup.sh

cache:
  directories:
  - /home/travis/external/vtk-6.0
  - /home/travis/external/vtk-6.0-build
  - /home/travis/external/vtk-6.3
  - /home/travis/external/vtk-6.3-build

before_script:

  - mkdir build
  - cd build
  - if [ ${DEBUG} == "YES" ]; then 
    cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_UNIT_TESTS=ON ..; else
    cmake ..;
    fi

script:
  - make
  - cd ../bin
  - ./Simple

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - if [ ${DEBUG} == "YES" ]; then
    make coveralls;
    fi

