language: cpp
compiler:
  - gcc
env:
  matrix:
    - DEBUG="YES"
    - DEBUG="NO"

before_script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=NXHsGpmqi6PpZHX8iM3OisE48frajQmFl

  - mkdir build
  - cd build
  - if [ ${DEBUG} == "YES" ]; then 
    cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_UNIT_TESTS=ON ..; else
    cmake ..;
    fi

script:
  - make
  - cd ../bin
  - ./Simple

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - if [ ${DEBUG} == "YES" ]; then
    make coveralls;
    fi

